/* Generated by JTB 1.4.7 */
package flame.syntaxtree;

import flame.visitor.*;

public class JavaStaticMethods implements INode {

  public NodeToken f0;

  public NodeList f1;

  public NodeToken f2;

  public MathExpression f3;

  public NodeListOptional f4;

  public NodeToken f5;

  public NodeToken f6;

  private static final long serialVersionUID = 147L;

  public JavaStaticMethods(final NodeToken n0, final NodeList n1, final NodeToken n2, final MathExpression n3, final NodeListOptional n4, final NodeToken n5, final NodeToken n6) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
